 Create a null vector of size 10 but the fifth value which is 1 

In [5]:
import numpy as np
arr = np.zeros(10)
arr[4] = 1
arr


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Create a vector with values ranging from 10 to 49

In [7]:
arr1 = np.arange(10,49)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

Reverse  a vector

In [14]:
arr = np.array([1,2,3,4,5,6])
arr_rev = np.flip(arr)
arr_rev

array([6, 5, 4, 3, 2, 1])

 Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr.shape

(3, 3)

 Find indices of non-zero elements from [1,2,0,0,4,0]
 

In [28]:
arr = np.array([1,2,0,0,4,0])
print(np.nonzero(arr)[0])

[0 1 4]


In [24]:
np.nonzero?

Signature: np.nonzero(a)
Docstring:
Return the indices of the elements that are non-zero.

Returns a tuple of arrays, one for each dimension of `a`,
containing the indices of the non-zero elements in that
dimension. The values in `a` are always tested and returned in
row-major, C-style order.

To group the indices by element, rather than dimension, use `argwhere`,
which returns a row for each non-zero element.

.. note::

   When called on a zero-d array or scalar, ``nonzero(a)`` is treated
   as ``nonzero(atleast_1d(a))``.

   .. deprecated:: 1.17.0

      Use `atleast_1d` explicitly if this behavior is deliberate.

Parameters
----------
a : array_like
    Input array.

Returns
-------
tuple_of_arrays : tuple
    Indices of elements that are non-zero.

See Also
--------
flatnonzero :
    Return indices that are non-zero in the flattened version of the input
    array.
ndarray.nonzero :
    Equivalent ndarray method.
count_nonzero :
    Counts the number of non-zero elements in the inp

 Create a 3x3x3 array with random values

In [52]:
arr = np.random.randint(0,10,size=(3,3,3))
arr

array([[[3, 7, 2],
        [2, 7, 3],
        [9, 6, 2]],

       [[5, 8, 3],
        [6, 7, 4],
        [2, 6, 2]],

       [[5, 7, 8],
        [7, 2, 0],
        [3, 9, 2]]])

Create a 10x10 array with random values and find the minimum and maximum values

In [51]:
arr = np.random.randint(0,10, size=(10,10))
# print("Max",arr.max())
# print("Min",arr.min())
print(arr)


[[9 6 1 1 1 7 1 4 2 9]
 [8 0 6 2 8 9 9 6 1 9]
 [3 1 2 2 6 1 9 3 5 8]
 [7 6 9 7 2 4 4 4 9 4]
 [9 9 3 6 9 7 8 7 3 5]
 [4 7 2 0 2 2 6 3 3 3]
 [4 8 1 4 5 4 7 9 3 1]
 [9 7 2 3 2 5 6 9 9 0]
 [6 1 8 4 8 9 1 7 7 5]
 [9 3 5 3 1 5 8 9 4 6]]


Create a 2d array with 1 on the border and 0 inside


In [71]:
arr = np.zeros((4,4), dtype = int)
arr[0, :] = 1  # Top Row
arr[: , 0] = 1 # Left Column
arr[: ,-1] = 1 # Right column
arr[-1, :] = 1 # Bottom column
arr

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [61]:
arr.dtype

dtype('int32')